### ISSUE TITLE
你好，可以分享这篇论文和完整源码吗

### ISSUE THREAD

**Issue by Ren-Owen** [nnnyt/QuesCo#1]
你好，可以分享这篇论文和完整源码吗

**Comment by nnnyt** [comment]
augment.py之前上传有误，现在已经更新了，感谢提醒。论文可以查阅：https://arxiv.org/abs/2301.07558

**Comment by Ren-Owen** [comment]
> augment.py之前上传有误，现在已经更新了，感谢提醒。论文可以查阅：https://arxiv.org/abs/2301.07558

感谢分享，十分感谢！～
